---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - AFTER_SCRIPT="true"
  matrix:
    - PHANTOM=phantomjs PHANTOM_V=1.* SCRIPT="test"
    - PHANTOM=phantomjs-prebuilt PHANTOM_V=* SCRIPT="test"
    - PHANTOM=phantomjs-prebuilt PHANTOM_V=* SCRIPT="test:sauce" AFTER_SCRIPT="ember sauce:disconnect"

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPXRyZW50bXdpbGxpcwo=`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9MjExZDUxOTAtNWQxYS00YzYzLWFhOGYtMjA1YmIzYzRlMGZmCg==`
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install $PHANTOM@$PHANTOM_V
  - node_modules/$PHANTOM/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm run test:node
  - npm run $SCRIPT

after_script:
  - $AFTER_SCRIPT
